package pigeon.backend.pigeondalback.entity;

public class Batch {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_info.item_id
     *
     * @mbg.generated
     */
    private String itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_info.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_info.uom
     *
     * @mbg.generated
     */
    private Integer uom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_info.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_info.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_info.current_package_id
     *
     * @mbg.generated
     */
    private String currentPackageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_info.unit_number
     *
     * @mbg.generated
     */
    private Integer unitNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_info.id
     *
     * @return the value of batch_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_info.id
     *
     * @param id the value for batch_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_info.item_id
     *
     * @return the value of batch_info.item_id
     *
     * @mbg.generated
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_info.item_id
     *
     * @param itemId the value for batch_info.item_id
     *
     * @mbg.generated
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_info.name
     *
     * @return the value of batch_info.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_info.name
     *
     * @param name the value for batch_info.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_info.uom
     *
     * @return the value of batch_info.uom
     *
     * @mbg.generated
     */
    public Integer getUom() {
        return uom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_info.uom
     *
     * @param uom the value for batch_info.uom
     *
     * @mbg.generated
     */
    public void setUom(Integer uom) {
        this.uom = uom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_info.status
     *
     * @return the value of batch_info.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_info.status
     *
     * @param status the value for batch_info.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_info.user_id
     *
     * @return the value of batch_info.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_info.user_id
     *
     * @param userId the value for batch_info.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_info.current_package_id
     *
     * @return the value of batch_info.current_package_id
     *
     * @mbg.generated
     */
    public String getCurrentPackageId() {
        return currentPackageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_info.current_package_id
     *
     * @param currentPackageId the value for batch_info.current_package_id
     *
     * @mbg.generated
     */
    public void setCurrentPackageId(String currentPackageId) {
        this.currentPackageId = currentPackageId == null ? null : currentPackageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_info.unit_number
     *
     * @return the value of batch_info.unit_number
     *
     * @mbg.generated
     */
    public Integer getUnitNumber() {
        return unitNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_info.unit_number
     *
     * @param unitNumber the value for batch_info.unit_number
     *
     * @mbg.generated
     */
    public void setUnitNumber(Integer unitNumber) {
        this.unitNumber = unitNumber;
    }
}