package pigeon.backend.pigeondalback.entity;

public class Inventory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_info.inventory_id
     *
     * @mbg.generated
     */
    private String inventoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_info.location
     *
     * @mbg.generated
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_info.capacity
     *
     * @mbg.generated
     */
    private Integer capacity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_info.id
     *
     * @return the value of inventory_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_info.id
     *
     * @param id the value for inventory_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_info.inventory_id
     *
     * @return the value of inventory_info.inventory_id
     *
     * @mbg.generated
     */
    public String getInventoryId() {
        return inventoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_info.inventory_id
     *
     * @param inventoryId the value for inventory_info.inventory_id
     *
     * @mbg.generated
     */
    public void setInventoryId(String inventoryId) {
        this.inventoryId = inventoryId == null ? null : inventoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_info.location
     *
     * @return the value of inventory_info.location
     *
     * @mbg.generated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_info.location
     *
     * @param location the value for inventory_info.location
     *
     * @mbg.generated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_info.capacity
     *
     * @return the value of inventory_info.capacity
     *
     * @mbg.generated
     */
    public Integer getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_info.capacity
     *
     * @param capacity the value for inventory_info.capacity
     *
     * @mbg.generated
     */
    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }
}