package pigeon.backend.pigeondalback.entity;

import java.util.Date;

public class Package {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_info.package_id
     *
     * @mbg.generated
     */
    private String packageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_info.destination
     *
     * @mbg.generated
     */
    private String destination;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_info.arrival_time
     *
     * @mbg.generated
     */
    private Date arrivalTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_info.tracking_id
     *
     * @mbg.generated
     */
    private String trackingId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_info.id
     *
     * @return the value of package_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_info.id
     *
     * @param id the value for package_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_info.package_id
     *
     * @return the value of package_info.package_id
     *
     * @mbg.generated
     */
    public String getPackageId() {
        return packageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_info.package_id
     *
     * @param packageId the value for package_info.package_id
     *
     * @mbg.generated
     */
    public void setPackageId(String packageId) {
        this.packageId = packageId == null ? null : packageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_info.destination
     *
     * @return the value of package_info.destination
     *
     * @mbg.generated
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_info.destination
     *
     * @param destination the value for package_info.destination
     *
     * @mbg.generated
     */
    public void setDestination(String destination) {
        this.destination = destination == null ? null : destination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_info.arrival_time
     *
     * @return the value of package_info.arrival_time
     *
     * @mbg.generated
     */
    public Date getArrivalTime() {
        return arrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_info.arrival_time
     *
     * @param arrivalTime the value for package_info.arrival_time
     *
     * @mbg.generated
     */
    public void setArrivalTime(Date arrivalTime) {
        this.arrivalTime = arrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_info.tracking_id
     *
     * @return the value of package_info.tracking_id
     *
     * @mbg.generated
     */
    public String getTrackingId() {
        return trackingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_info.tracking_id
     *
     * @param trackingId the value for package_info.tracking_id
     *
     * @mbg.generated
     */
    public void setTrackingId(String trackingId) {
        this.trackingId = trackingId == null ? null : trackingId.trim();
    }
}